#!/bin/bash

#================Dream network parameters=================
network='dream4'
numofnode=(10 100)
networknum=(1 2 3 4 5)
discretization=('efd' 'ewd' 'kmeans')

path="$PWD"

results='results'
source='sourcefiles'
code='code'
disclevel='3bin'
#Set variant to 1 for PEPN-GRN_v1 and 2 for PEPN-GRN_v2
variant=1

mkdir ./$results
cd ./$results

for nn in "${numofnode[@]}"
do 
	for netnum in "${networknum[@]}"
	do
	currentNet=$network'_'$nn'_'$netnum

	mkdir ./$currentNet
	cd ./$currentNet
	echo $currentNet
		#==============================PEPN-GRN code=======================================

		for disc in "${discretization[@]}"
		do
		mkdir ./$disc
		cd ./$disc
		echo $disc
				gdtruth='gdTruth_'$currentNet
				cp $path/$source/*.m .
				cp $path/multi-bin-disc-dream4-data-repository/$currentNet/*.{mat,tsv,csv} .
				cp $path/multi-bin-disc-dream4-data-repository/$currentNet/$disc/*.mat .
				cp $path/multi-bin-disc-dream4-data-repository/*.mat .
	
				matlab -nodisplay -nosplash -nodesktop -r "run $code($nn,$netnum,'$disc','$disclevel',$variant).m; run edge_features($nn,$netnum).m; quit;"
				
				#===================== ROC and PR plots generated by RANKWISE method =============
				matlab -nodisplay -nosplash -nodesktop -r "run rankwise_roc_pr_plot($nn,$netnum).m; quit;"
							
		cd ..		
		done
	cd ..			
	done
done
cd ..


